name: Terraform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-checks:
    name: Terraform Check - ${{ matrix.layer }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        layer:
          - "Networking"

    defaults:
      run:
        working-directory: ./${{ matrix.layer }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate